version: '3.8'  # Specify the Compose file format version

services:
  app:
    build:
      context: .           # Build context is the current directory
      dockerfile: Dockerfile  # Use the Dockerfile in the current directory for building the image
    ports:
      - "3000:3000"        # Map host port 3000 to container port 3000
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/chat_with_openai"  # Set the database URL environment variable for the app
      OPENAI_API_KEY: "${OPENAI_API_KEY}"  # Pass the OpenAI API key from the host environment
    volumes:
      - .:/app             # Mount the current directory into /app inside the container for live code updates
    depends_on:
      - db                 # Ensure the 'db' service is started before this 'app' service

  db:
    image: postgres:15     # Use the Postgres 15 image for the database service
    restart: always        # Always restart the container if it stops
    ports:
      - "5432:5432"        # Map host port 5432 to container port 5432 for Postgres
    environment:
      POSTGRES_USER: postgres        # Set Postgres user
      POSTGRES_PASSWORD: postgres    # Set Postgres password
      POSTGRES_DB: chat_with_openai  # Create/use the 'chat_with_openai' database
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist Postgres data using a Docker volume

volumes:
  postgres_data:  # Define a named volume 'postgres_data' for persisting database data
